#!/bin/sh
# vim: set ts=4:
#
# Runs linters, tests etc.
#
# This script follows convention https://github.com/github/scripts-to-rule-them-all.
# Original source: https://gist.github.com/jirutka/c5200ddcf00a86603314988fcad9532f
set -u

# This if block ensures script can be sourced.
if [ -z "${D_BASE+x}" ] ; then # if unset or empty
	_SCRIPT_REL_TO_BASE='../'
	D_SCRIPT="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
	D_BASE="${D_SCRIPT}/${_SCRIPT_REL_TO_BASE}"
	readonly \
		D_BASE \
		D_SCRIPT
	unset \
		_SCRIPT_REL_TO_BASE
fi

cd "${D_BASE}" || exit 1

. "./scripts/bootstrap"

# NOTE: This was used to avoid checking ENV_DIR
D_PYPACKAGE="kas"
readonly D_PYPACKAGE

ERROR=0

info "Checking with pycodestyle"
pycodestyle --ignore=W503,W606 *.py $D_PYPACKAGE/*.py || ERROR=$(expr $ERROR + 1)

info "Checking with flake8"
flake8 $D_PYPACKAGE || ERROR=$(expr $ERROR + 2)

info "Checking with doc8"
doc8  "docs" --ignore-path "docs/_build" || ERROR=$(expr $ERROR + 4)

info "Checking with shellcheck"
shellcheck -S warning kas-docker scripts/release.sh scripts/checkcode.sh || ERROR=$(expr $ERROR + 8)

exit $ERROR
